FROM node:20-bullseye

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y wine64 wine32 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

COPY . .

RUN npm run build

RUN npx electron-builder --win --x64

CMD ["cp", "-r", "/app/release/.", "/output/"]
